appName: checkoutservice
appImage: gcr.io/google-samples/microservices-demo/checkoutservice
appVersion: v0.8.1
appReplicas: 2
containerPort: 5050
containerEnvVars:
- name: PORT
  value: "5050"
- name: PRODUCT_CATALOG_SERVICE_ADDR
  value: "productcatalogservice:3550"
- name: SHIPPING_SERVICE_ADDR
  value: "shippingservice:50051"
- name: PAYMENT_SERVICE_ADDR
  value: "paymentservice:50051"
- name: EMAIL_SERVICE_ADDR
  value: "emailservice:5000"
- name: CURRENCY_SERVICE_ADDR
  value: "currencyservice:7000"
- name: CART_SERVICE_ADDR
  value: "cartservice:7070"
- name: DISABLE_TRACING
  value: "1"
- name: DISABLE_PROFILER
  value: "1"

servicePort: 5050

readinessProbePeriodSeconds: 0
grpcPort: 5050
livenessProbePeriodSeconds: 0
limitsMemory: 128Mi
limitsCPU: 200m
requestsCPU: 100m
requestsMemory: 64Mi

