appName: emailservice
appImage: gcr.io/google-samples/microservices-demo/emailservice
appVersion: v0.8.1
appReplicas: 2
containerPort: 8080
containerEnvVars:
- name: PORT
  value: "8080"
- name: DISABLE_TRACING
  value: "1"
- name: DISABLE_PROFILER
  value: "1"

servicePort: 5000

readinessProbePeriodSeconds: 5
grpcPort: 8080
livenessProbePeriodSeconds: 5
limitsMemory: 128Mi
limitsCPU: 200m
requestsCPU: 100m
requestsMemory: 64Mi


