appName: productcatalogservice
appImage: gcr.io/google-samples/microservices-demo/productcatalogservice
appVersion: v0.8.1
appReplicas: 2
containerPort: 3550
containerEnvVars:
- name: PORT
  value: "3550"
- name: DISABLE_TRACING
  value: "1"
- name: DISABLE_PROFILER
  value: "1"

servicePort: 3550

readinessProbePeriodSeconds: 0
initialDelaySeconds: 0
grpcPort: 3550
livenessProbePeriodSeconds: 0
limitsMemory: 128Mi
limitsCPU: 200m
requestsCPU: 100m
requestsMemory: 64Mi


