appName: recommendationservice
appImage: gcr.io/google-samples/microservices-demo/recommendationservice
appVersion: v0.8.1
appReplicas: 2
containerPort: 8080
containerEnvVars:
- name: PORT
  value: "8080"
- name: PRODUCT_CATALOG_SERVICE_ADDR
  value: "productcatalogservice:3550"
- name: DISABLE_TRACING
  value: "1"
- name: DISABLE_PROFILER
  value: "1"

servicePort: 8080

readinessProbePeriodSeconds: 5
initialDelaySeconds: 0
grpcPort: 8080
livenessProbePeriodSeconds: 5
limitsMemory: 450Mi
limitsCPU: 200m
requestsCPU: 100m
requestsMemory: 220Mi

