appName: servicename
appImage: gcr.io/google-samples/microservices-demo/servicename
appVersion: v.0.0.0
appReplicas: 1
containerPort: 8080
containerEnvVars:
- name: ENV_VAR_ONE
  value: "valueone"
- name: ENV_VAR_TWO
  value: "valuetwo"

servicePort: 8080
serviceType: ClusterIP 

readinessProbePeriodSeconds: 5
initialDelaySeconds: 0
grpcPort: 6379
livenessProbePeriodSeconds: 5
limitsMemory: 256Mi
limitsCPU: 125m
requestsCPU: 70m
requestsMemory: 200Mi
